version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html  
    depends_on:
      - postgres
    # Artisan serve command works flawlessly here
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - ocp_network

  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: stage_ocp
      POSTGRES_USER: mouad  
      POSTGRES_PASSWORD: mouad
    ports:
      - "5432:5432"
    volumes:
      - pgtables:/var/lib/postgresql/data 
    networks:
      - ocp_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mouad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mouad
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - ocp_network

  frontend:
    image: node:20-alpine 
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ocp_network
    depends_on:
      - backend

networks:
  ocp_network:
    driver: bridge

volumes:
  pgtables: